# Generated by Django 5.2.10 on 2026-01-28 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_actividades.actividad')),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('gestion_actividades.actividad',),
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_actividades.actividad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('nivel_avance', models.PositiveIntegerField(default=0)),
            ],
            bases=('gestion_actividades.actividad',),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_actividades.actividad')),
                ('completada', models.BooleanField(default=False)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('gestion_actividades.actividad',),
        ),
    ]
