# Generated by Django 5.2.10 on 2026-01-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
